[package]
name = "alicesaidhi/kibble"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["**"]
include = ["src", "src/*", "default.project.json", "wally.lock", "wally.toml"]

[dependencies]
vide = "aloroid/vide-with-types@0.2.3"